# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Build settings
#remote_theme: fduperier/bolby-jekyll
theme: bolby-jekyll
sass:
  style: expanded
kramdown:
  hard_wrap: true

# Site
repository: fduperier/fduperier.github.io
#favicon: assets/favicon.ico
lang: en_US
gtag: UA-17165966-5
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.frederic-duperier.com" # the base hostname & protocol for your site, e.g. http://example.com

# Personal info
name: Frédéric Dupérier
title: Frédéric Dupérier | Solutions Architect with Entrepreneurial mindset
email: fduperier@gmail.com
rotation_text: Solutions Architect, Project Technical Leader, Web & Mobile Developer, Certified Scrum Developer, Certified Scrum Master

description: >- # this means to ignore newlines
  Frédéric Dupérier is a Solutions Architect with Entrepreneurial mindset.
  He's the founder of We Are One Sàrl, a consulting, software development and training company based in Geneva, Switzerland.



# About Section
about_title: About Me
about_profile_image: "assets/images/profile.png"
about_content: >-
  I am <b>Frédéric Dupérier</b>, Solutions Architect & Entrepreneur.
  I am the founder of We Are One Sàrl, a consulting, software development and training company based in Geneva, Switzerland.
#about_action: Download CV
about_link: '#'

# Service section
service_title: Services
service_subtitle: Looking for a custom job?
service_action: Click here
service_link: '#contact'
service_action_unlinked: to contact me! 👋


# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# Contact Section
contact_title: Get In Touch
contact_subtitle: Let's talk about everything!
contact_form_action: https://formspree.io/mwkrqpyg


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

# SEO settings
# Documentation at https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
author: Frédéric Dupérier
logo: /assets/profile.png
twitter:
  username: fduperier
  card: summary
facebook:
#  app_id: 1234
  publisher: 100933041817895
  admins: 736337098
social:
  name: Frédéric Dupérier
  links:
    - https://f-d.me/linkedin
    - https://f-d.me/github
    - https://f-d.me/gitlab
    - https://f-d.me/twitter
    - https://f-d.me/fb
    - https://f-d.me/insta
    - https://f-d.me/whatsapp
#webmaster_verifications:
#  google:
#  bing:
#  alexa:
#  yandex:
#  baidu:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
