# Service template
- title: Engineering Management
  picture: /assets/images/undraw_good_team_m7uu_blue.svg
  description: I can help you manage engineering teams.
  style_class: text-light shadow-pink
  color: '#FF4C60'

- title: Solution Architecture
  picture: /assets/images/undraw_programming_2svr_red.svg
  description: Whatever your problems, I can suggest you several solutions and then help you manage them.
  style_class: shadow-yellow
  color: '#FFD15C'

- title: Agile DevOps
  picture: /assets/images/undraw_version_control_9bpv_yellow.svg
  description: I can help you design a new CI/CD environment for your Agile projects.
  style_class: text-light shadow-blue
  color: '#6C6CE5'
